async def receive_heartbeat_timeout(): ...


async def receive_candidate_timeout(): ...


async def receive_heartbeat(data: object): ...


async def receive_vote(vote: bool): ...


async def request_votes(): ...
